GET http://localhost:3000/todos

###
POST http://localhost:3000/todos/new
Content-Type: application/json

{
    "text": "order chicken"
}

###
DELETE http://localhost:3000/todos/delete/64f1ae79f9cb70001ab0e067